/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.model.Estudiante;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author edwar
 */
public class TablaEstudiantes extends javax.swing.JDialog {

    /**
     * Creates new form TablaEstudiantes
     */
    public TablaEstudiantes(java.awt.Frame parent, boolean modal, List dto) {
        super(parent, modal);
        initComponents();
        tabla(dto);
    }
    
    private void tabla(List<Estudiante> lista){
        Object matriz[][] = new Object [lista.size()][8];
        for(int i = 0; i < lista.size(); i++){
            matriz[i][0]=lista.get(i).getNombres();
            matriz[i][1]=lista.get(i).getApellidos();
            matriz[i][2]=lista.get(i).getFechaNacimiento();
            matriz[i][3]=lista.get(i).getCorreo1();
            matriz[i][4]=lista.get(i).getCorreo2();
            matriz[i][5]=lista.get(i).getCelular();
            matriz[i][6]=lista.get(i).getFijo();
            matriz[i][7]=lista.get(i).getPrograma();

        }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String [] {
                    "Nombres", "Apellidos", "Fecha nacimiento:", "Correo institucional:", "Correo personal:", "Número de teléfono celular:", "Número de teléfono fijo:", "Programa académico:"
                }
            ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        claseTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Fecha nacimiento:", "Correo institucional:", "Correo personal:", "Número de teléfono celular:", "Número de teléfono fijo:", "Programa académico:"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        claseTable.setText("Cerrar");
        claseTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claseTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(claseTable)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(claseTable)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claseTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claseTableActionPerformed
        dispose();
    }//GEN-LAST:event_claseTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List<Estudiante> lista = new ArrayList();
                TablaEstudiantes dialog = new TablaEstudiantes(new javax.swing.JFrame(), true, lista);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton claseTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
